from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.eppcom_ext_auth_info_type import EppcomExtAuthInfoType
from openapi_server import util

from openapi_server.models.eppcom_ext_auth_info_type import EppcomExtAuthInfoType  # noqa: E501

class DomainAuthInfoChgTypeOneOf1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ext=None):  # noqa: E501
        """DomainAuthInfoChgTypeOneOf1 - a model defined in OpenAPI

        :param ext: The ext of this DomainAuthInfoChgTypeOneOf1.  # noqa: E501
        :type ext: EppcomExtAuthInfoType
        """
        self.openapi_types = {
            'ext': EppcomExtAuthInfoType
        }

        self.attribute_map = {
            'ext': 'ext'
        }

        self._ext = ext

    @classmethod
    def from_dict(cls, dikt) -> 'DomainAuthInfoChgTypeOneOf1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain_authInfoChgType_oneOf_1 of this DomainAuthInfoChgTypeOneOf1.  # noqa: E501
        :rtype: DomainAuthInfoChgTypeOneOf1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ext(self) -> EppcomExtAuthInfoType:
        """Gets the ext of this DomainAuthInfoChgTypeOneOf1.


        :return: The ext of this DomainAuthInfoChgTypeOneOf1.
        :rtype: EppcomExtAuthInfoType
        """
        return self._ext

    @ext.setter
    def ext(self, ext: EppcomExtAuthInfoType):
        """Sets the ext of this DomainAuthInfoChgTypeOneOf1.


        :param ext: The ext of this DomainAuthInfoChgTypeOneOf1.
        :type ext: EppcomExtAuthInfoType
        """
        if ext is None:
            raise ValueError("Invalid value for `ext`, must not be `None`")  # noqa: E501

        self._ext = ext
