from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DomainContactAttrType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ADMIN = 'admin'
    BILLING = 'billing'
    TECH = 'tech'
    def __init__(self):  # noqa: E501
        """DomainContactAttrType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DomainContactAttrType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain_contactAttrType of this DomainContactAttrType.  # noqa: E501
        :rtype: DomainContactAttrType
        """
        return util.deserialize_model(dikt, cls)
