from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DomainContactType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value=None, type=None):  # noqa: E501
        """DomainContactType - a model defined in OpenAPI

        :param value: The value of this DomainContactType.  # noqa: E501
        :type value: str
        :param type: The type of this DomainContactType.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'value': str,
            'type': str
        }

        self.attribute_map = {
            'value': '#value',
            'type': '@type'
        }

        self._value = value
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'DomainContactType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain_contactType of this DomainContactType.  # noqa: E501
        :rtype: DomainContactType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> str:
        """Gets the value of this DomainContactType.


        :return: The value of this DomainContactType.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this DomainContactType.


        :param value: The value of this DomainContactType.
        :type value: str
        """
        if value is not None and len(value) > 16:
            raise ValueError("Invalid value for `value`, length must be less than or equal to `16`")  # noqa: E501
        if value is not None and len(value) < 3:
            raise ValueError("Invalid value for `value`, length must be greater than or equal to `3`")  # noqa: E501

        self._value = value

    @property
    def type(self) -> str:
        """Gets the type of this DomainContactType.


        :return: The type of this DomainContactType.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this DomainContactType.


        :param type: The type of this DomainContactType.
        :type type: str
        """
        allowed_values = ["admin", "billing", "tech"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type
