from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DomainPeriodType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value=None, unit=None):  # noqa: E501
        """DomainPeriodType - a model defined in OpenAPI

        :param value: The value of this DomainPeriodType.  # noqa: E501
        :type value: int
        :param unit: The unit of this DomainPeriodType.  # noqa: E501
        :type unit: str
        """
        self.openapi_types = {
            'value': int,
            'unit': str
        }

        self.attribute_map = {
            'value': '#value',
            'unit': '@unit'
        }

        self._value = value
        self._unit = unit

    @classmethod
    def from_dict(cls, dikt) -> 'DomainPeriodType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain_periodType of this DomainPeriodType.  # noqa: E501
        :rtype: DomainPeriodType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> int:
        """Gets the value of this DomainPeriodType.


        :return: The value of this DomainPeriodType.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value: int):
        """Sets the value of this DomainPeriodType.


        :param value: The value of this DomainPeriodType.
        :type value: int
        """
        if value is not None and value > 99:  # noqa: E501
            raise ValueError("Invalid value for `value`, must be a value less than or equal to `99`")  # noqa: E501
        if value is not None and value < 1:  # noqa: E501
            raise ValueError("Invalid value for `value`, must be a value greater than or equal to `1`")  # noqa: E501

        self._value = value

    @property
    def unit(self) -> str:
        """Gets the unit of this DomainPeriodType.


        :return: The unit of this DomainPeriodType.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit: str):
        """Sets the unit of this DomainPeriodType.


        :param unit: The unit of this DomainPeriodType.
        :type unit: str
        """
        allowed_values = ["y", "m"]  # noqa: E501
        if unit not in allowed_values:
            raise ValueError(
                "Invalid value for `unit` ({0}), must be one of {1}"
                .format(unit, allowed_values)
            )

        self._unit = unit
