from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DomainNsTypeOneOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, host_obj=None):  # noqa: E501
        """DomainNsTypeOneOf - a model defined in OpenAPI

        :param host_obj: The host_obj of this DomainNsTypeOneOf.  # noqa: E501
        :type host_obj: List[str]
        """
        self.openapi_types = {
            'host_obj': List[str]
        }

        self.attribute_map = {
            'host_obj': 'hostObj'
        }

        self._host_obj = host_obj

    @classmethod
    def from_dict(cls, dikt) -> 'DomainNsTypeOneOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain_nsType_oneOf of this DomainNsTypeOneOf.  # noqa: E501
        :rtype: DomainNsTypeOneOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def host_obj(self) -> List[str]:
        """Gets the host_obj of this DomainNsTypeOneOf.


        :return: The host_obj of this DomainNsTypeOneOf.
        :rtype: List[str]
        """
        return self._host_obj

    @host_obj.setter
    def host_obj(self, host_obj: List[str]):
        """Sets the host_obj of this DomainNsTypeOneOf.


        :param host_obj: The host_obj of this DomainNsTypeOneOf.
        :type host_obj: List[str]
        """
        if host_obj is not None and len(host_obj) < 1:
            raise ValueError("Invalid value for `host_obj`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._host_obj = host_obj
