from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DomainHostsType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ALL = 'all'
    DEL = 'del'
    NONE = 'none'
    SUB = 'sub'
    def __init__(self):  # noqa: E501
        """DomainHostsType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DomainHostsType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain_hostsType of this DomainHostsType.  # noqa: E501
        :rtype: DomainHostsType
        """
        return util.deserialize_model(dikt, cls)
