from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.sec_dnsds_or_key_type import SecDNSDsOrKeyType
from openapi_server import util

from openapi_server.models.sec_dnsds_or_key_type import SecDNSDsOrKeyType  # noqa: E501

class DomainCreateRequestAllOfCommandExtension(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sec_dns=None):  # noqa: E501
        """DomainCreateRequestAllOfCommandExtension - a model defined in OpenAPI

        :param sec_dns: The sec_dns of this DomainCreateRequestAllOfCommandExtension.  # noqa: E501
        :type sec_dns: SecDNSDsOrKeyType
        """
        self.openapi_types = {
            'sec_dns': SecDNSDsOrKeyType
        }

        self.attribute_map = {
            'sec_dns': 'secDNS'
        }

        self._sec_dns = sec_dns

    @classmethod
    def from_dict(cls, dikt) -> 'DomainCreateRequestAllOfCommandExtension':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DomainCreateRequest_allOf_command_extension of this DomainCreateRequestAllOfCommandExtension.  # noqa: E501
        :rtype: DomainCreateRequestAllOfCommandExtension
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sec_dns(self) -> SecDNSDsOrKeyType:
        """Gets the sec_dns of this DomainCreateRequestAllOfCommandExtension.


        :return: The sec_dns of this DomainCreateRequestAllOfCommandExtension.
        :rtype: SecDNSDsOrKeyType
        """
        return self._sec_dns

    @sec_dns.setter
    def sec_dns(self, sec_dns: SecDNSDsOrKeyType):
        """Sets the sec_dns of this DomainCreateRequestAllOfCommandExtension.


        :param sec_dns: The sec_dns of this DomainCreateRequestAllOfCommandExtension.
        :type sec_dns: SecDNSDsOrKeyType
        """

        self._sec_dns = sec_dns
