from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.domain_period_type import DomainPeriodType
from openapi_server import util

from openapi_server.models.domain_period_type import DomainPeriodType  # noqa: E501

class DomainRenewType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cur_exp_date=None, name=None, period=None):  # noqa: E501
        """DomainRenewType - a model defined in OpenAPI

        :param cur_exp_date: The cur_exp_date of this DomainRenewType.  # noqa: E501
        :type cur_exp_date: date
        :param name: The name of this DomainRenewType.  # noqa: E501
        :type name: str
        :param period: The period of this DomainRenewType.  # noqa: E501
        :type period: DomainPeriodType
        """
        self.openapi_types = {
            'cur_exp_date': date,
            'name': str,
            'period': DomainPeriodType
        }

        self.attribute_map = {
            'cur_exp_date': 'curExpDate',
            'name': 'name',
            'period': 'period'
        }

        self._cur_exp_date = cur_exp_date
        self._name = name
        self._period = period

    @classmethod
    def from_dict(cls, dikt) -> 'DomainRenewType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain_renewType of this DomainRenewType.  # noqa: E501
        :rtype: DomainRenewType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cur_exp_date(self) -> date:
        """Gets the cur_exp_date of this DomainRenewType.


        :return: The cur_exp_date of this DomainRenewType.
        :rtype: date
        """
        return self._cur_exp_date

    @cur_exp_date.setter
    def cur_exp_date(self, cur_exp_date: date):
        """Sets the cur_exp_date of this DomainRenewType.


        :param cur_exp_date: The cur_exp_date of this DomainRenewType.
        :type cur_exp_date: date
        """
        if cur_exp_date is None:
            raise ValueError("Invalid value for `cur_exp_date`, must not be `None`")  # noqa: E501

        self._cur_exp_date = cur_exp_date

    @property
    def name(self) -> str:
        """Gets the name of this DomainRenewType.


        :return: The name of this DomainRenewType.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this DomainRenewType.


        :param name: The name of this DomainRenewType.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 255:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def period(self) -> DomainPeriodType:
        """Gets the period of this DomainRenewType.


        :return: The period of this DomainRenewType.
        :rtype: DomainPeriodType
        """
        return self._period

    @period.setter
    def period(self, period: DomainPeriodType):
        """Sets the period of this DomainRenewType.


        :param period: The period of this DomainRenewType.
        :type period: DomainPeriodType
        """

        self._period = period
