from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.domain_pa_name_type import DomainPaNameType
from openapi_server.models.epp_tr_id_type import EppTrIDType
from openapi_server import util

from openapi_server.models.domain_pa_name_type import DomainPaNameType  # noqa: E501
from openapi_server.models.epp_tr_id_type import EppTrIDType  # noqa: E501

class DomainPanDataType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, pa_date=None, pa_trid=None):  # noqa: E501
        """DomainPanDataType - a model defined in OpenAPI

        :param name: The name of this DomainPanDataType.  # noqa: E501
        :type name: DomainPaNameType
        :param pa_date: The pa_date of this DomainPanDataType.  # noqa: E501
        :type pa_date: datetime
        :param pa_trid: The pa_trid of this DomainPanDataType.  # noqa: E501
        :type pa_trid: EppTrIDType
        """
        self.openapi_types = {
            'name': DomainPaNameType,
            'pa_date': datetime,
            'pa_trid': EppTrIDType
        }

        self.attribute_map = {
            'name': 'name',
            'pa_date': 'paDate',
            'pa_trid': 'paTRID'
        }

        self._name = name
        self._pa_date = pa_date
        self._pa_trid = pa_trid

    @classmethod
    def from_dict(cls, dikt) -> 'DomainPanDataType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain_panDataType of this DomainPanDataType.  # noqa: E501
        :rtype: DomainPanDataType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> DomainPaNameType:
        """Gets the name of this DomainPanDataType.


        :return: The name of this DomainPanDataType.
        :rtype: DomainPaNameType
        """
        return self._name

    @name.setter
    def name(self, name: DomainPaNameType):
        """Sets the name of this DomainPanDataType.


        :param name: The name of this DomainPanDataType.
        :type name: DomainPaNameType
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def pa_date(self) -> datetime:
        """Gets the pa_date of this DomainPanDataType.


        :return: The pa_date of this DomainPanDataType.
        :rtype: datetime
        """
        return self._pa_date

    @pa_date.setter
    def pa_date(self, pa_date: datetime):
        """Sets the pa_date of this DomainPanDataType.


        :param pa_date: The pa_date of this DomainPanDataType.
        :type pa_date: datetime
        """
        if pa_date is None:
            raise ValueError("Invalid value for `pa_date`, must not be `None`")  # noqa: E501

        self._pa_date = pa_date

    @property
    def pa_trid(self) -> EppTrIDType:
        """Gets the pa_trid of this DomainPanDataType.


        :return: The pa_trid of this DomainPanDataType.
        :rtype: EppTrIDType
        """
        return self._pa_trid

    @pa_trid.setter
    def pa_trid(self, pa_trid: EppTrIDType):
        """Sets the pa_trid of this DomainPanDataType.


        :param pa_trid: The pa_trid of this DomainPanDataType.
        :type pa_trid: EppTrIDType
        """
        if pa_trid is None:
            raise ValueError("Invalid value for `pa_trid`, must not be `None`")  # noqa: E501

        self._pa_trid = pa_trid
