from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DomainStatusValueType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    CLIENTDELETEPROHIBITED = 'clientDeleteProhibited'
    CLIENTHOLD = 'clientHold'
    CLIENTRENEWPROHIBITED = 'clientRenewProhibited'
    CLIENTTRANSFERPROHIBITED = 'clientTransferProhibited'
    CLIENTUPDATEPROHIBITED = 'clientUpdateProhibited'
    INACTIVE = 'inactive'
    OK = 'ok'
    PENDINGCREATE = 'pendingCreate'
    PENDINGDELETE = 'pendingDelete'
    PENDINGRENEW = 'pendingRenew'
    PENDINGTRANSFER = 'pendingTransfer'
    PENDINGUPDATE = 'pendingUpdate'
    SERVERDELETEPROHIBITED = 'serverDeleteProhibited'
    SERVERHOLD = 'serverHold'
    SERVERRENEWPROHIBITED = 'serverRenewProhibited'
    SERVERTRANSFERPROHIBITED = 'serverTransferProhibited'
    SERVERUPDATEPROHIBITED = 'serverUpdateProhibited'
    def __init__(self):  # noqa: E501
        """DomainStatusValueType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DomainStatusValueType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain_statusValueType of this DomainStatusValueType.  # noqa: E501
        :rtype: DomainStatusValueType
        """
        return util.deserialize_model(dikt, cls)
