from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.domain_check_name_type import DomainCheckNameType
from openapi_server.models.eppcom_reason_type import EppcomReasonType
from openapi_server import util

from openapi_server.models.domain_check_name_type import DomainCheckNameType  # noqa: E501
from openapi_server.models.eppcom_reason_type import EppcomReasonType  # noqa: E501

class DomainCheckType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, reason=None):  # noqa: E501
        """DomainCheckType - a model defined in OpenAPI

        :param name: The name of this DomainCheckType.  # noqa: E501
        :type name: DomainCheckNameType
        :param reason: The reason of this DomainCheckType.  # noqa: E501
        :type reason: EppcomReasonType
        """
        self.openapi_types = {
            'name': DomainCheckNameType,
            'reason': EppcomReasonType
        }

        self.attribute_map = {
            'name': 'name',
            'reason': 'reason'
        }

        self._name = name
        self._reason = reason

    @classmethod
    def from_dict(cls, dikt) -> 'DomainCheckType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain_checkType of this DomainCheckType.  # noqa: E501
        :rtype: DomainCheckType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> DomainCheckNameType:
        """Gets the name of this DomainCheckType.


        :return: The name of this DomainCheckType.
        :rtype: DomainCheckNameType
        """
        return self._name

    @name.setter
    def name(self, name: DomainCheckNameType):
        """Sets the name of this DomainCheckType.


        :param name: The name of this DomainCheckType.
        :type name: DomainCheckNameType
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def reason(self) -> EppcomReasonType:
        """Gets the reason of this DomainCheckType.


        :return: The reason of this DomainCheckType.
        :rtype: EppcomReasonType
        """
        return self._reason

    @reason.setter
    def reason(self, reason: EppcomReasonType):
        """Sets the reason of this DomainCheckType.


        :param reason: The reason of this DomainCheckType.
        :type reason: EppcomReasonType
        """

        self._reason = reason
