from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DomainInfoNameType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value=None, hosts=None):  # noqa: E501
        """DomainInfoNameType - a model defined in OpenAPI

        :param value: The value of this DomainInfoNameType.  # noqa: E501
        :type value: str
        :param hosts: The hosts of this DomainInfoNameType.  # noqa: E501
        :type hosts: str
        """
        self.openapi_types = {
            'value': str,
            'hosts': str
        }

        self.attribute_map = {
            'value': '#value',
            'hosts': '@hosts'
        }

        self._value = value
        self._hosts = hosts

    @classmethod
    def from_dict(cls, dikt) -> 'DomainInfoNameType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain_infoNameType of this DomainInfoNameType.  # noqa: E501
        :rtype: DomainInfoNameType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> str:
        """Gets the value of this DomainInfoNameType.


        :return: The value of this DomainInfoNameType.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this DomainInfoNameType.


        :param value: The value of this DomainInfoNameType.
        :type value: str
        """
        if value is not None and len(value) > 255:
            raise ValueError("Invalid value for `value`, length must be less than or equal to `255`")  # noqa: E501
        if value is not None and len(value) < 1:
            raise ValueError("Invalid value for `value`, length must be greater than or equal to `1`")  # noqa: E501

        self._value = value

    @property
    def hosts(self) -> str:
        """Gets the hosts of this DomainInfoNameType.


        :return: The hosts of this DomainInfoNameType.
        :rtype: str
        """
        return self._hosts

    @hosts.setter
    def hosts(self, hosts: str):
        """Sets the hosts of this DomainInfoNameType.


        :param hosts: The hosts of this DomainInfoNameType.
        :type hosts: str
        """
        allowed_values = ["all", "del", "none", "sub"]  # noqa: E501
        if hosts not in allowed_values:
            raise ValueError(
                "Invalid value for `hosts` ({0}), must be one of {1}"
                .format(hosts, allowed_values)
            )

        self._hosts = hosts
