from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.eppcom_tr_status_type import EppcomTrStatusType
from openapi_server import util

from openapi_server.models.eppcom_tr_status_type import EppcomTrStatusType  # noqa: E501

class DomainTrnDataType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ac_date=None, ac_id=None, ex_date=None, name=None, re_date=None, re_id=None, tr_status=None):  # noqa: E501
        """DomainTrnDataType - a model defined in OpenAPI

        :param ac_date: The ac_date of this DomainTrnDataType.  # noqa: E501
        :type ac_date: datetime
        :param ac_id: The ac_id of this DomainTrnDataType.  # noqa: E501
        :type ac_id: str
        :param ex_date: The ex_date of this DomainTrnDataType.  # noqa: E501
        :type ex_date: datetime
        :param name: The name of this DomainTrnDataType.  # noqa: E501
        :type name: str
        :param re_date: The re_date of this DomainTrnDataType.  # noqa: E501
        :type re_date: datetime
        :param re_id: The re_id of this DomainTrnDataType.  # noqa: E501
        :type re_id: str
        :param tr_status: The tr_status of this DomainTrnDataType.  # noqa: E501
        :type tr_status: EppcomTrStatusType
        """
        self.openapi_types = {
            'ac_date': datetime,
            'ac_id': str,
            'ex_date': datetime,
            'name': str,
            're_date': datetime,
            're_id': str,
            'tr_status': EppcomTrStatusType
        }

        self.attribute_map = {
            'ac_date': 'acDate',
            'ac_id': 'acID',
            'ex_date': 'exDate',
            'name': 'name',
            're_date': 'reDate',
            're_id': 'reID',
            'tr_status': 'trStatus'
        }

        self._ac_date = ac_date
        self._ac_id = ac_id
        self._ex_date = ex_date
        self._name = name
        self._re_date = re_date
        self._re_id = re_id
        self._tr_status = tr_status

    @classmethod
    def from_dict(cls, dikt) -> 'DomainTrnDataType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain_trnDataType of this DomainTrnDataType.  # noqa: E501
        :rtype: DomainTrnDataType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ac_date(self) -> datetime:
        """Gets the ac_date of this DomainTrnDataType.


        :return: The ac_date of this DomainTrnDataType.
        :rtype: datetime
        """
        return self._ac_date

    @ac_date.setter
    def ac_date(self, ac_date: datetime):
        """Sets the ac_date of this DomainTrnDataType.


        :param ac_date: The ac_date of this DomainTrnDataType.
        :type ac_date: datetime
        """
        if ac_date is None:
            raise ValueError("Invalid value for `ac_date`, must not be `None`")  # noqa: E501

        self._ac_date = ac_date

    @property
    def ac_id(self) -> str:
        """Gets the ac_id of this DomainTrnDataType.


        :return: The ac_id of this DomainTrnDataType.
        :rtype: str
        """
        return self._ac_id

    @ac_id.setter
    def ac_id(self, ac_id: str):
        """Sets the ac_id of this DomainTrnDataType.


        :param ac_id: The ac_id of this DomainTrnDataType.
        :type ac_id: str
        """
        if ac_id is None:
            raise ValueError("Invalid value for `ac_id`, must not be `None`")  # noqa: E501
        if ac_id is not None and len(ac_id) > 16:
            raise ValueError("Invalid value for `ac_id`, length must be less than or equal to `16`")  # noqa: E501
        if ac_id is not None and len(ac_id) < 3:
            raise ValueError("Invalid value for `ac_id`, length must be greater than or equal to `3`")  # noqa: E501

        self._ac_id = ac_id

    @property
    def ex_date(self) -> datetime:
        """Gets the ex_date of this DomainTrnDataType.


        :return: The ex_date of this DomainTrnDataType.
        :rtype: datetime
        """
        return self._ex_date

    @ex_date.setter
    def ex_date(self, ex_date: datetime):
        """Sets the ex_date of this DomainTrnDataType.


        :param ex_date: The ex_date of this DomainTrnDataType.
        :type ex_date: datetime
        """

        self._ex_date = ex_date

    @property
    def name(self) -> str:
        """Gets the name of this DomainTrnDataType.


        :return: The name of this DomainTrnDataType.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this DomainTrnDataType.


        :param name: The name of this DomainTrnDataType.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 255:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def re_date(self) -> datetime:
        """Gets the re_date of this DomainTrnDataType.


        :return: The re_date of this DomainTrnDataType.
        :rtype: datetime
        """
        return self._re_date

    @re_date.setter
    def re_date(self, re_date: datetime):
        """Sets the re_date of this DomainTrnDataType.


        :param re_date: The re_date of this DomainTrnDataType.
        :type re_date: datetime
        """
        if re_date is None:
            raise ValueError("Invalid value for `re_date`, must not be `None`")  # noqa: E501

        self._re_date = re_date

    @property
    def re_id(self) -> str:
        """Gets the re_id of this DomainTrnDataType.


        :return: The re_id of this DomainTrnDataType.
        :rtype: str
        """
        return self._re_id

    @re_id.setter
    def re_id(self, re_id: str):
        """Sets the re_id of this DomainTrnDataType.


        :param re_id: The re_id of this DomainTrnDataType.
        :type re_id: str
        """
        if re_id is None:
            raise ValueError("Invalid value for `re_id`, must not be `None`")  # noqa: E501
        if re_id is not None and len(re_id) > 16:
            raise ValueError("Invalid value for `re_id`, length must be less than or equal to `16`")  # noqa: E501
        if re_id is not None and len(re_id) < 3:
            raise ValueError("Invalid value for `re_id`, length must be greater than or equal to `3`")  # noqa: E501

        self._re_id = re_id

    @property
    def tr_status(self) -> EppcomTrStatusType:
        """Gets the tr_status of this DomainTrnDataType.


        :return: The tr_status of this DomainTrnDataType.
        :rtype: EppcomTrStatusType
        """
        return self._tr_status

    @tr_status.setter
    def tr_status(self, tr_status: EppcomTrStatusType):
        """Sets the tr_status of this DomainTrnDataType.


        :param tr_status: The tr_status of this DomainTrnDataType.
        :type tr_status: EppcomTrStatusType
        """
        if tr_status is None:
            raise ValueError("Invalid value for `tr_status`, must not be `None`")  # noqa: E501

        self._tr_status = tr_status
