from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class EppVersionType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ENUM_1_PERIOD_0 = '1.0'
    def __init__(self):  # noqa: E501
        """EppVersionType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'EppVersionType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_versionType of this EppVersionType.  # noqa: E501
        :rtype: EppVersionType
        """
        return util.deserialize_model(dikt, cls)
