from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class EppPollType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, msg_id=None, op=None):  # noqa: E501
        """EppPollType - a model defined in OpenAPI

        :param msg_id: The msg_id of this EppPollType.  # noqa: E501
        :type msg_id: str
        :param op: The op of this EppPollType.  # noqa: E501
        :type op: str
        """
        self.openapi_types = {
            'msg_id': str,
            'op': str
        }

        self.attribute_map = {
            'msg_id': '@msgID',
            'op': '@op'
        }

        self._msg_id = msg_id
        self._op = op

    @classmethod
    def from_dict(cls, dikt) -> 'EppPollType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_pollType of this EppPollType.  # noqa: E501
        :rtype: EppPollType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def msg_id(self) -> str:
        """Gets the msg_id of this EppPollType.


        :return: The msg_id of this EppPollType.
        :rtype: str
        """
        return self._msg_id

    @msg_id.setter
    def msg_id(self, msg_id: str):
        """Sets the msg_id of this EppPollType.


        :param msg_id: The msg_id of this EppPollType.
        :type msg_id: str
        """

        self._msg_id = msg_id

    @property
    def op(self) -> str:
        """Gets the op of this EppPollType.


        :return: The op of this EppPollType.
        :rtype: str
        """
        return self._op

    @op.setter
    def op(self, op: str):
        """Sets the op of this EppPollType.


        :param op: The op of this EppPollType.
        :type op: str
        """
        allowed_values = ["ack", "req"]  # noqa: E501
        if op not in allowed_values:
            raise ValueError(
                "Invalid value for `op` ({0}), must be one of {1}"
                .format(op, allowed_values)
            )

        self._op = op
