from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class EppDcpRetentionTypeOneOf2(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, legal=False):  # noqa: E501
        """EppDcpRetentionTypeOneOf2 - a model defined in OpenAPI

        :param legal: The legal of this EppDcpRetentionTypeOneOf2.  # noqa: E501
        :type legal: bool
        """
        self.openapi_types = {
            'legal': bool
        }

        self.attribute_map = {
            'legal': 'legal'
        }

        self._legal = legal

    @classmethod
    def from_dict(cls, dikt) -> 'EppDcpRetentionTypeOneOf2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_dcpRetentionType_oneOf_2 of this EppDcpRetentionTypeOneOf2.  # noqa: E501
        :rtype: EppDcpRetentionTypeOneOf2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def legal(self) -> bool:
        """Gets the legal of this EppDcpRetentionTypeOneOf2.


        :return: The legal of this EppDcpRetentionTypeOneOf2.
        :rtype: bool
        """
        return self._legal

    @legal.setter
    def legal(self, legal: bool):
        """Sets the legal of this EppDcpRetentionTypeOneOf2.


        :param legal: The legal of this EppDcpRetentionTypeOneOf2.
        :type legal: bool
        """
        if legal is None:
            raise ValueError("Invalid value for `legal`, must not be `None`")  # noqa: E501

        self._legal = legal
