from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class EppDcpAccessTypeOneOf4(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, personal_and_other=False):  # noqa: E501
        """EppDcpAccessTypeOneOf4 - a model defined in OpenAPI

        :param personal_and_other: The personal_and_other of this EppDcpAccessTypeOneOf4.  # noqa: E501
        :type personal_and_other: bool
        """
        self.openapi_types = {
            'personal_and_other': bool
        }

        self.attribute_map = {
            'personal_and_other': 'personalAndOther'
        }

        self._personal_and_other = personal_and_other

    @classmethod
    def from_dict(cls, dikt) -> 'EppDcpAccessTypeOneOf4':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_dcpAccessType_oneOf_4 of this EppDcpAccessTypeOneOf4.  # noqa: E501
        :rtype: EppDcpAccessTypeOneOf4
        """
        return util.deserialize_model(dikt, cls)

    @property
    def personal_and_other(self) -> bool:
        """Gets the personal_and_other of this EppDcpAccessTypeOneOf4.


        :return: The personal_and_other of this EppDcpAccessTypeOneOf4.
        :rtype: bool
        """
        return self._personal_and_other

    @personal_and_other.setter
    def personal_and_other(self, personal_and_other: bool):
        """Sets the personal_and_other of this EppDcpAccessTypeOneOf4.


        :param personal_and_other: The personal_and_other of this EppDcpAccessTypeOneOf4.
        :type personal_and_other: bool
        """
        if personal_and_other is None:
            raise ValueError("Invalid value for `personal_and_other`, must not be `None`")  # noqa: E501

        self._personal_and_other = personal_and_other
