from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class EppErrValueType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, text=None):  # noqa: E501
        """EppErrValueType - a model defined in OpenAPI

        :param text: The text of this EppErrValueType.  # noqa: E501
        :type text: List[str]
        """
        self.openapi_types = {
            'text': List[str]
        }

        self.attribute_map = {
            'text': '#text'
        }

        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'EppErrValueType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_errValueType of this EppErrValueType.  # noqa: E501
        :rtype: EppErrValueType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self) -> List[str]:
        """Gets the text of this EppErrValueType.


        :return: The text of this EppErrValueType.
        :rtype: List[str]
        """
        return self._text

    @text.setter
    def text(self, text: List[str]):
        """Sets the text of this EppErrValueType.


        :param text: The text of this EppErrValueType.
        :type text: List[str]
        """

        self._text = text
