from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.epp_ext_uri_type import EppExtURIType
from openapi_server import util

from openapi_server.models.epp_ext_uri_type import EppExtURIType  # noqa: E501

class EppLoginSvcType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, obj_uri=None, svc_extension=None):  # noqa: E501
        """EppLoginSvcType - a model defined in OpenAPI

        :param obj_uri: The obj_uri of this EppLoginSvcType.  # noqa: E501
        :type obj_uri: List[str]
        :param svc_extension: The svc_extension of this EppLoginSvcType.  # noqa: E501
        :type svc_extension: EppExtURIType
        """
        self.openapi_types = {
            'obj_uri': List[str],
            'svc_extension': EppExtURIType
        }

        self.attribute_map = {
            'obj_uri': 'objURI',
            'svc_extension': 'svcExtension'
        }

        self._obj_uri = obj_uri
        self._svc_extension = svc_extension

    @classmethod
    def from_dict(cls, dikt) -> 'EppLoginSvcType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_loginSvcType of this EppLoginSvcType.  # noqa: E501
        :rtype: EppLoginSvcType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def obj_uri(self) -> List[str]:
        """Gets the obj_uri of this EppLoginSvcType.


        :return: The obj_uri of this EppLoginSvcType.
        :rtype: List[str]
        """
        return self._obj_uri

    @obj_uri.setter
    def obj_uri(self, obj_uri: List[str]):
        """Sets the obj_uri of this EppLoginSvcType.


        :param obj_uri: The obj_uri of this EppLoginSvcType.
        :type obj_uri: List[str]
        """
        if obj_uri is not None and len(obj_uri) < 1:
            raise ValueError("Invalid value for `obj_uri`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._obj_uri = obj_uri

    @property
    def svc_extension(self) -> EppExtURIType:
        """Gets the svc_extension of this EppLoginSvcType.


        :return: The svc_extension of this EppLoginSvcType.
        :rtype: EppExtURIType
        """
        return self._svc_extension

    @svc_extension.setter
    def svc_extension(self, svc_extension: EppExtURIType):
        """Sets the svc_extension of this EppLoginSvcType.


        :param svc_extension: The svc_extension of this EppLoginSvcType.
        :type svc_extension: EppExtURIType
        """

        self._svc_extension = svc_extension
