from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class EppDcpRetentionTypeOneOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, business=False):  # noqa: E501
        """EppDcpRetentionTypeOneOf - a model defined in OpenAPI

        :param business: The business of this EppDcpRetentionTypeOneOf.  # noqa: E501
        :type business: bool
        """
        self.openapi_types = {
            'business': bool
        }

        self.attribute_map = {
            'business': 'business'
        }

        self._business = business

    @classmethod
    def from_dict(cls, dikt) -> 'EppDcpRetentionTypeOneOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_dcpRetentionType_oneOf of this EppDcpRetentionTypeOneOf.  # noqa: E501
        :rtype: EppDcpRetentionTypeOneOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def business(self) -> bool:
        """Gets the business of this EppDcpRetentionTypeOneOf.


        :return: The business of this EppDcpRetentionTypeOneOf.
        :rtype: bool
        """
        return self._business

    @business.setter
    def business(self, business: bool):
        """Sets the business of this EppDcpRetentionTypeOneOf.


        :param business: The business of this EppDcpRetentionTypeOneOf.
        :type business: bool
        """
        if business is None:
            raise ValueError("Invalid value for `business`, must not be `None`")  # noqa: E501

        self._business = business
