from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.epp_ext_any_type import EppExtAnyType
from openapi_server.models.epp_login_type import EppLoginType
from openapi_server.models.epp_poll_type import EppPollType
from openapi_server.models.epp_read_write_type import EppReadWriteType
from openapi_server.models.epp_transfer_type import EppTransferType
from openapi_server import util

from openapi_server.models.epp_ext_any_type import EppExtAnyType  # noqa: E501
from openapi_server.models.epp_login_type import EppLoginType  # noqa: E501
from openapi_server.models.epp_poll_type import EppPollType  # noqa: E501
from openapi_server.models.epp_read_write_type import EppReadWriteType  # noqa: E501
from openapi_server.models.epp_transfer_type import EppTransferType  # noqa: E501

class EppCommandType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cl_trid=None, extension=None, check=None, create=None, delete=None, info=None, login=None, logout=False, poll=None, renew=None, transfer=None, update=None):  # noqa: E501
        """EppCommandType - a model defined in OpenAPI

        :param cl_trid: The cl_trid of this EppCommandType.  # noqa: E501
        :type cl_trid: str
        :param extension: The extension of this EppCommandType.  # noqa: E501
        :type extension: EppExtAnyType
        :param check: The check of this EppCommandType.  # noqa: E501
        :type check: EppReadWriteType
        :param create: The create of this EppCommandType.  # noqa: E501
        :type create: EppReadWriteType
        :param delete: The delete of this EppCommandType.  # noqa: E501
        :type delete: EppReadWriteType
        :param info: The info of this EppCommandType.  # noqa: E501
        :type info: EppReadWriteType
        :param login: The login of this EppCommandType.  # noqa: E501
        :type login: EppLoginType
        :param logout: The logout of this EppCommandType.  # noqa: E501
        :type logout: bool
        :param poll: The poll of this EppCommandType.  # noqa: E501
        :type poll: EppPollType
        :param renew: The renew of this EppCommandType.  # noqa: E501
        :type renew: EppReadWriteType
        :param transfer: The transfer of this EppCommandType.  # noqa: E501
        :type transfer: EppTransferType
        :param update: The update of this EppCommandType.  # noqa: E501
        :type update: EppReadWriteType
        """
        self.openapi_types = {
            'cl_trid': str,
            'extension': EppExtAnyType,
            'check': EppReadWriteType,
            'create': EppReadWriteType,
            'delete': EppReadWriteType,
            'info': EppReadWriteType,
            'login': EppLoginType,
            'logout': bool,
            'poll': EppPollType,
            'renew': EppReadWriteType,
            'transfer': EppTransferType,
            'update': EppReadWriteType
        }

        self.attribute_map = {
            'cl_trid': 'clTRID',
            'extension': 'extension',
            'check': 'check',
            'create': 'create',
            'delete': 'delete',
            'info': 'info',
            'login': 'login',
            'logout': 'logout',
            'poll': 'poll',
            'renew': 'renew',
            'transfer': 'transfer',
            'update': 'update'
        }

        self._cl_trid = cl_trid
        self._extension = extension
        self._check = check
        self._create = create
        self._delete = delete
        self._info = info
        self._login = login
        self._logout = logout
        self._poll = poll
        self._renew = renew
        self._transfer = transfer
        self._update = update

    @classmethod
    def from_dict(cls, dikt) -> 'EppCommandType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The epp_commandType of this EppCommandType.  # noqa: E501
        :rtype: EppCommandType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cl_trid(self) -> str:
        """Gets the cl_trid of this EppCommandType.


        :return: The cl_trid of this EppCommandType.
        :rtype: str
        """
        return self._cl_trid

    @cl_trid.setter
    def cl_trid(self, cl_trid: str):
        """Sets the cl_trid of this EppCommandType.


        :param cl_trid: The cl_trid of this EppCommandType.
        :type cl_trid: str
        """
        if cl_trid is not None and len(cl_trid) > 64:
            raise ValueError("Invalid value for `cl_trid`, length must be less than or equal to `64`")  # noqa: E501
        if cl_trid is not None and len(cl_trid) < 3:
            raise ValueError("Invalid value for `cl_trid`, length must be greater than or equal to `3`")  # noqa: E501

        self._cl_trid = cl_trid

    @property
    def extension(self) -> EppExtAnyType:
        """Gets the extension of this EppCommandType.


        :return: The extension of this EppCommandType.
        :rtype: EppExtAnyType
        """
        return self._extension

    @extension.setter
    def extension(self, extension: EppExtAnyType):
        """Sets the extension of this EppCommandType.


        :param extension: The extension of this EppCommandType.
        :type extension: EppExtAnyType
        """

        self._extension = extension

    @property
    def check(self) -> EppReadWriteType:
        """Gets the check of this EppCommandType.


        :return: The check of this EppCommandType.
        :rtype: EppReadWriteType
        """
        return self._check

    @check.setter
    def check(self, check: EppReadWriteType):
        """Sets the check of this EppCommandType.


        :param check: The check of this EppCommandType.
        :type check: EppReadWriteType
        """
        if check is None:
            raise ValueError("Invalid value for `check`, must not be `None`")  # noqa: E501

        self._check = check

    @property
    def create(self) -> EppReadWriteType:
        """Gets the create of this EppCommandType.


        :return: The create of this EppCommandType.
        :rtype: EppReadWriteType
        """
        return self._create

    @create.setter
    def create(self, create: EppReadWriteType):
        """Sets the create of this EppCommandType.


        :param create: The create of this EppCommandType.
        :type create: EppReadWriteType
        """
        if create is None:
            raise ValueError("Invalid value for `create`, must not be `None`")  # noqa: E501

        self._create = create

    @property
    def delete(self) -> EppReadWriteType:
        """Gets the delete of this EppCommandType.


        :return: The delete of this EppCommandType.
        :rtype: EppReadWriteType
        """
        return self._delete

    @delete.setter
    def delete(self, delete: EppReadWriteType):
        """Sets the delete of this EppCommandType.


        :param delete: The delete of this EppCommandType.
        :type delete: EppReadWriteType
        """
        if delete is None:
            raise ValueError("Invalid value for `delete`, must not be `None`")  # noqa: E501

        self._delete = delete

    @property
    def info(self) -> EppReadWriteType:
        """Gets the info of this EppCommandType.


        :return: The info of this EppCommandType.
        :rtype: EppReadWriteType
        """
        return self._info

    @info.setter
    def info(self, info: EppReadWriteType):
        """Sets the info of this EppCommandType.


        :param info: The info of this EppCommandType.
        :type info: EppReadWriteType
        """
        if info is None:
            raise ValueError("Invalid value for `info`, must not be `None`")  # noqa: E501

        self._info = info

    @property
    def login(self) -> EppLoginType:
        """Gets the login of this EppCommandType.


        :return: The login of this EppCommandType.
        :rtype: EppLoginType
        """
        return self._login

    @login.setter
    def login(self, login: EppLoginType):
        """Sets the login of this EppCommandType.


        :param login: The login of this EppCommandType.
        :type login: EppLoginType
        """
        if login is None:
            raise ValueError("Invalid value for `login`, must not be `None`")  # noqa: E501

        self._login = login

    @property
    def logout(self) -> bool:
        """Gets the logout of this EppCommandType.


        :return: The logout of this EppCommandType.
        :rtype: bool
        """
        return self._logout

    @logout.setter
    def logout(self, logout: bool):
        """Sets the logout of this EppCommandType.


        :param logout: The logout of this EppCommandType.
        :type logout: bool
        """
        if logout is None:
            raise ValueError("Invalid value for `logout`, must not be `None`")  # noqa: E501

        self._logout = logout

    @property
    def poll(self) -> EppPollType:
        """Gets the poll of this EppCommandType.


        :return: The poll of this EppCommandType.
        :rtype: EppPollType
        """
        return self._poll

    @poll.setter
    def poll(self, poll: EppPollType):
        """Sets the poll of this EppCommandType.


        :param poll: The poll of this EppCommandType.
        :type poll: EppPollType
        """
        if poll is None:
            raise ValueError("Invalid value for `poll`, must not be `None`")  # noqa: E501

        self._poll = poll

    @property
    def renew(self) -> EppReadWriteType:
        """Gets the renew of this EppCommandType.


        :return: The renew of this EppCommandType.
        :rtype: EppReadWriteType
        """
        return self._renew

    @renew.setter
    def renew(self, renew: EppReadWriteType):
        """Sets the renew of this EppCommandType.


        :param renew: The renew of this EppCommandType.
        :type renew: EppReadWriteType
        """
        if renew is None:
            raise ValueError("Invalid value for `renew`, must not be `None`")  # noqa: E501

        self._renew = renew

    @property
    def transfer(self) -> EppTransferType:
        """Gets the transfer of this EppCommandType.


        :return: The transfer of this EppCommandType.
        :rtype: EppTransferType
        """
        return self._transfer

    @transfer.setter
    def transfer(self, transfer: EppTransferType):
        """Sets the transfer of this EppCommandType.


        :param transfer: The transfer of this EppCommandType.
        :type transfer: EppTransferType
        """
        if transfer is None:
            raise ValueError("Invalid value for `transfer`, must not be `None`")  # noqa: E501

        self._transfer = transfer

    @property
    def update(self) -> EppReadWriteType:
        """Gets the update of this EppCommandType.


        :return: The update of this EppCommandType.
        :rtype: EppReadWriteType
        """
        return self._update

    @update.setter
    def update(self, update: EppReadWriteType):
        """Sets the update of this EppCommandType.


        :param update: The update of this EppCommandType.
        :type update: EppReadWriteType
        """
        if update is None:
            raise ValueError("Invalid value for `update`, must not be `None`")  # noqa: E501

        self._update = update
