from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class EppcomExtAuthInfoType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """EppcomExtAuthInfoType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'EppcomExtAuthInfoType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The eppcom_extAuthInfoType of this EppcomExtAuthInfoType.  # noqa: E501
        :rtype: EppcomExtAuthInfoType
        """
        return util.deserialize_model(dikt, cls)
