from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.host_add_rem_type import HostAddRemType
from openapi_server.models.host_chg_type import HostChgType
from openapi_server import util

from openapi_server.models.host_add_rem_type import HostAddRemType  # noqa: E501
from openapi_server.models.host_chg_type import HostChgType  # noqa: E501

class HostUpdateType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, add=None, chg=None, name=None, rem=None):  # noqa: E501
        """HostUpdateType - a model defined in OpenAPI

        :param add: The add of this HostUpdateType.  # noqa: E501
        :type add: HostAddRemType
        :param chg: The chg of this HostUpdateType.  # noqa: E501
        :type chg: HostChgType
        :param name: The name of this HostUpdateType.  # noqa: E501
        :type name: str
        :param rem: The rem of this HostUpdateType.  # noqa: E501
        :type rem: HostAddRemType
        """
        self.openapi_types = {
            'add': HostAddRemType,
            'chg': HostChgType,
            'name': str,
            'rem': HostAddRemType
        }

        self.attribute_map = {
            'add': 'add',
            'chg': 'chg',
            'name': 'name',
            'rem': 'rem'
        }

        self._add = add
        self._chg = chg
        self._name = name
        self._rem = rem

    @classmethod
    def from_dict(cls, dikt) -> 'HostUpdateType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The host_updateType of this HostUpdateType.  # noqa: E501
        :rtype: HostUpdateType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def add(self) -> HostAddRemType:
        """Gets the add of this HostUpdateType.


        :return: The add of this HostUpdateType.
        :rtype: HostAddRemType
        """
        return self._add

    @add.setter
    def add(self, add: HostAddRemType):
        """Sets the add of this HostUpdateType.


        :param add: The add of this HostUpdateType.
        :type add: HostAddRemType
        """

        self._add = add

    @property
    def chg(self) -> HostChgType:
        """Gets the chg of this HostUpdateType.


        :return: The chg of this HostUpdateType.
        :rtype: HostChgType
        """
        return self._chg

    @chg.setter
    def chg(self, chg: HostChgType):
        """Sets the chg of this HostUpdateType.


        :param chg: The chg of this HostUpdateType.
        :type chg: HostChgType
        """

        self._chg = chg

    @property
    def name(self) -> str:
        """Gets the name of this HostUpdateType.


        :return: The name of this HostUpdateType.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this HostUpdateType.


        :param name: The name of this HostUpdateType.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 255:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def rem(self) -> HostAddRemType:
        """Gets the rem of this HostUpdateType.


        :return: The rem of this HostUpdateType.
        :rtype: HostAddRemType
        """
        return self._rem

    @rem.setter
    def rem(self, rem: HostAddRemType):
        """Sets the rem of this HostUpdateType.


        :param rem: The rem of this HostUpdateType.
        :type rem: HostAddRemType
        """

        self._rem = rem
