from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.host_check_type import HostCheckType
from openapi_server import util

from openapi_server.models.host_check_type import HostCheckType  # noqa: E501

class HostChkDataType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cd=None):  # noqa: E501
        """HostChkDataType - a model defined in OpenAPI

        :param cd: The cd of this HostChkDataType.  # noqa: E501
        :type cd: List[HostCheckType]
        """
        self.openapi_types = {
            'cd': List[HostCheckType]
        }

        self.attribute_map = {
            'cd': 'cd'
        }

        self._cd = cd

    @classmethod
    def from_dict(cls, dikt) -> 'HostChkDataType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The host_chkDataType of this HostChkDataType.  # noqa: E501
        :rtype: HostChkDataType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cd(self) -> List[HostCheckType]:
        """Gets the cd of this HostChkDataType.


        :return: The cd of this HostChkDataType.
        :rtype: List[HostCheckType]
        """
        return self._cd

    @cd.setter
    def cd(self, cd: List[HostCheckType]):
        """Sets the cd of this HostChkDataType.


        :param cd: The cd of this HostChkDataType.
        :type cd: List[HostCheckType]
        """
        if cd is None:
            raise ValueError("Invalid value for `cd`, must not be `None`")  # noqa: E501
        if cd is not None and len(cd) < 1:
            raise ValueError("Invalid value for `cd`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._cd = cd
