from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.sec_dnsds_data_type import SecDNSDsDataType
from openapi_server import util

from openapi_server.models.sec_dnsds_data_type import SecDNSDsDataType  # noqa: E501

class SecDNSRemTypeOneOf1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ds_data=None):  # noqa: E501
        """SecDNSRemTypeOneOf1 - a model defined in OpenAPI

        :param ds_data: The ds_data of this SecDNSRemTypeOneOf1.  # noqa: E501
        :type ds_data: List[SecDNSDsDataType]
        """
        self.openapi_types = {
            'ds_data': List[SecDNSDsDataType]
        }

        self.attribute_map = {
            'ds_data': 'dsData'
        }

        self._ds_data = ds_data

    @classmethod
    def from_dict(cls, dikt) -> 'SecDNSRemTypeOneOf1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The secDNS_remType_oneOf_1 of this SecDNSRemTypeOneOf1.  # noqa: E501
        :rtype: SecDNSRemTypeOneOf1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ds_data(self) -> List[SecDNSDsDataType]:
        """Gets the ds_data of this SecDNSRemTypeOneOf1.


        :return: The ds_data of this SecDNSRemTypeOneOf1.
        :rtype: List[SecDNSDsDataType]
        """
        return self._ds_data

    @ds_data.setter
    def ds_data(self, ds_data: List[SecDNSDsDataType]):
        """Sets the ds_data of this SecDNSRemTypeOneOf1.


        :param ds_data: The ds_data of this SecDNSRemTypeOneOf1.
        :type ds_data: List[SecDNSDsDataType]
        """
        if ds_data is None:
            raise ValueError("Invalid value for `ds_data`, must not be `None`")  # noqa: E501
        if ds_data is not None and len(ds_data) < 1:
            raise ValueError("Invalid value for `ds_data`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._ds_data = ds_data
